export const DB_COLLECTIONS = {
  ADMIN: 'admin',
  USERS: 'user',
  NOFIFICATION: 'notification',
  CONTEST: 'contest',
  NEWS: 'news',
  VERIFICATIONS: 'verification',
  TEAMS: 'team',
  PLAYER: 'player',
  PLAYER_PREDICTION_SCORE: 'player_prediction_scores',
  DEFENSE_TEAM_PREDICTION_SCORE: 'defense_team_prediction_score',
  PLAYER_LIVE_SCORE: 'player_live_score',
  GEAR: 'gear',
  INVENTORY: 'inventories',
  NFT: 'nft',
  METADATA: 'metadata',
  LISTING: 'listing',
  CHALLENGES: 'challenges',
  MATCH: 'match',
  ROSTER: 'roster',
  GAMESTATS: 'gamestats',
  RAPIDTANK01_PLAYERS: 'rapidtank01_players',
  RAPIDTANK01_PROJECTION_GAME: 'rapidtank01_projection_game',
  RAPIDTANK01_TEAM_SCHEDULE: 'rapidtank01_team_schedule',
};
